### ISSUE TITLE
Failed to launch phantomjs

### ISSUE THREAD

**Issue by youvere** [LonnyGomes/World-Factbook-Data-Parser#3]
What is the set up you use to run the parser ? I tried develop and master branch and i have the same error 

ERROR Error: Error processing dumps:Error: Failed to launch phantomjs for phantomjs/scrapeCountryFlags.js

this is the version of phantomjs I'm using 
phantomjs@1.9.2-4
│ ├── adm-zip@0.2.1
│ ├── kew@0.1.7
│ ├── mkdirp@0.3.5
│ ├── ncp@0.4.2
│ ├─┬ npmconf@0.0.24
│ │ ├─┬ config-chain@1.1.8
│ │ │ └── proto-list@1.2.3
│ │ ├── inherits@1.0.0
│ │ ├── ini@1.1.0
│ │ ├─┬ nopt@2.2.1
│ │ │ └── abbrev@1.0.5
│ │ ├── once@1.1.1
│ │ ├── osenv@0.0.3
│ │ └── semver@1.1.4
│ ├── rimraf@2.2.8
│ └── which@1.0.8

Downloading dumps/index.zip ... done
Downloading dumps/docs.zip ... done
Downloading dumps/js.zip ... done
Downloading dumps/scripts.zip ... done
Downloading dumps/rankorder.zip ... done
Successfully downloaded all required data dumps

Extracting dumps/index.zip ... done
Extracting dumps/docs.zip ... done
Extracting dumps/js.zip ... done
Extracting dumps/scripts.zip ... done
Extracting dumps/rankorder.zip ... done
Processing dump files ... 
    Processing country flags page
    Processing rank order page

ERROR Error: Error processing dumps:Error: Failed to launch phantomjs for phantomjs/scrapeCountryFlags.js

I use those versions
"dependencies": {
    "phantomjs": "~1.9.2-4",
    "ya-csv": "~0.9.2",
    "wget": "0.0.1",
    "q": "~1.0.0",
    "q-io": "~1.10.6",
    "adm-zip": "~0.4.3",
    "underscore": "~1.5.2",
    "colors": "~0.6.2"
  },

Thanks for help

**Comment by LonnyGomes** [comment]
@youvere can you give it a try in the develop branch again? I added more verbose error messages. The odd thing is that phantomjs should be running locally.

**Comment by youvere** [comment]
thanks that's what i needed to solve my problem
